<?php

use Illuminate\Database\Migrations\Migration;

class AddDisciplinesTags extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // populate disciplines
        DB::table('tags')->insert(
            [
                ['name' => "Aeroacoustics", 'category' => "Acoustics", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Hydrodynamic noise", 'category' => "Acoustics", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Jet noise", 'category' => "Acoustics", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Noise control", 'category' => "Acoustics", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Waves in random media", 'category' => "Acoustics", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Flow-structure interactions", 'category' => "Aerodynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "High-speed flow", 'category' => "Aerodynamics", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Bioconvection", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Biomedical flows", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Blood flow", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Capsule/cell dynamics", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Flow-vessel interactions", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Membranes", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Micro-organism dynamics", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Peristaltic pumping", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Propulsion", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Pulmonary fluid mechanics", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Swimming/flying", 'category' => "Biological Fluid Dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Boundary layer control", 'category' => "Boundary Layers",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Free shear layers", 'category' => "Boundary Layers",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Pipe flow boundary layer", 'category' => "Boundary Layers",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Boundary layer receptivity", 'category' => "Boundary Layers",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Boundary layer separation", 'category' => "Boundary Layers",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Boundary layer stability", 'category' => "Boundary Layers",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Boundary layer structure", 'category' => "Boundary Layers",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Colloids", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Dielectrics", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Emulsions", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Foams", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Granular media", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Liquid crystals", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Quantum fluids", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Suspensions", 'category' => "Complex Fluids", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Compressible boundary layers", 'category' => "Compressible Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Detonation waves", 'category' => "Compressible Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Gas dynamics", 'category' => "Compressible Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Shock waves", 'category' => "Compressible Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "B�nard convection", 'category' => "Convection", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Buoyant boundary layers", 'category' => "Convection",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Convection in cavities", 'category' => "Convection",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Double diffusive convection", 'category' => "Convection",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Buoyancy-driven instability", 'category' => "Convection",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Marangoni convection", 'category' => "Convection", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Moist convection", 'category' => "Convection", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Plumes/thermals", 'category' => "Convection", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Convection in porous media", 'category' => "Convection",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Taylor-Couette flow", 'category' => "Convection", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Aerosols/atomization", 'category' => "Drops and Bubbles",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Boiling", 'category' => "Drops and Bubbles", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Breakup/coalescence", 'category' => "Drops and Bubbles",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Bubble dynamics", 'category' => "Drops and Bubbles",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Cavitation", 'category' => "Drops and Bubbles", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Drops", 'category' => "Drops and Bubbles", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Electrohydrodynamic effects", 'category' => "Drops and Bubbles",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Sonoluminescence", 'category' => "Drops and Bubbles",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Thermocapillarity", 'category' => "Drops and Bubbles",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Control theory", 'category' => "Flow Control", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Drag reduction", 'category' => "Flow Control", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Instability control", 'category' => "Flow Control", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Mixing enhancement", 'category' => "Flow Control", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Air/sea interactions", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Atmospheric flows", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Baroclinic flows", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Coastal engineering", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Geodynamo", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Geostrophic turbulence", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Gravity currents", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Hydraulic control", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Ice sheets", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Internal waves", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Magma and lava flow", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Mantle convection", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Meteorology", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Mixing and dispersion", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Ocean circulation", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Ocean processes", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Quasi-geostrophic flows", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "River dynamics", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Rotating flows", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Sediment transport", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Sea ice", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Shallow water flows", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Stratified flows", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Topographic effects", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Waves in rotating fluids", 'category' => "Geophysical and Geological Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Absolute/convective instability", 'category' => "Instability",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Nonlinear instability", 'category' => "Instability",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Parametric instability", 'category' => "Instability",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Transition to turbulence", 'category' => "Instability",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Capillary flows", 'category' => "Interfacial Flows (free surface)",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Contact lines", 'category' => "Interfacial Flows (free surface)",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Fingering instability", 'category' => "Interfacial Flows (free surface)",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Liquid bridges", 'category' => "Interfacial Flows (free surface)",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Thin films", 'category' => "Interfacial Flows (free surface)",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Lubrication theory", 'category' => "Low-Reynolds-number flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Boundary integral methods", 'category' => "Low-Reynolds-number flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Hele-Shaw flows", 'category' => "Low-Reynolds-number flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Porous media", 'category' => "Low-Reynolds-number flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Slender-body theory", 'category' => "Low-Reynolds-number flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Stokesian dynamics", 'category' => "Low-Reynolds-number flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Coating", 'category' => "Materials Processing Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Magnetohydrodynamics", 'category' => "Materials Processing Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Microelectronics", 'category' => "Materials Processing Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Polymer processing", 'category' => "Materials Processing Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Computational methods", 'category' => "Mathematical Foundations",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "General fluid mechanics", 'category' => "Mathematical Foundations",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Hamiltonian theory", 'category' => "Mathematical Foundations",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Navier⿿Stokes equations", 'category' => "Mathematical Foundations",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Topological fluid dynamics", 'category' => "Mathematical Foundations",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Variational methods", 'category' => "Mathematical Foundations",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Dynamo theory", 'category' => "MHD and Electrohydrodynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "High-Hartmann-number flows", 'category' => "MHD and Electrohydrodynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Magnetic fluids", 'category' => "MHD and Electrohydrodynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Magneto convection", 'category' => "MHD and Electrohydrodynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "MHD turbulence", 'category' => "MHD and Electrohydrodynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Plasmas", 'category' => "MHD and Electrohydrodynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "MEMS/NEMS", 'category' => "Micro-/Nano-fluid dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Microfluidics", 'category' => "Micro-/Nano-fluid dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Non-continuum effects", 'category' => "Micro-/Nano-fluid dynamics",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Chaotic advection", 'category' => "Mixing", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Granular mixing", 'category' => "Mixing", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulent mixing", 'category' => "Mixing", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Alluvial dynamics", 'category' => "Multiphase and Particle-laden Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Core-annular flow", 'category' => "Multiphase and Particle-laden Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Fluidized beds", 'category' => "Multiphase and Particle-laden Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Gas/liquid flow", 'category' => "Multiphase and Particle-laden Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Multiphase flow", 'category' => "Multiphase and Particle-laden Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Particle/fluid flow", 'category' => "Multiphase and Particle-laden Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Reacting multiphase flow", 'category' => "Multiphase and Particle-laden Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Plastic materials", 'category' => "Non-Newtonian Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Polymers", 'category' => "Non-Newtonian Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Rheology", 'category' => "Non-Newtonian Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Viscoelasticity", 'category' => "Non-Newtonian Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Bifurcation", 'category' => "Nonlinear Dynamical Systems",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Chaos", 'category' => "Nonlinear Dynamical Systems",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Fractals", 'category' => "Nonlinear Dynamical Systems",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Low-dimensional models", 'category' => "Nonlinear Dynamical Systems",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Pattern formation", 'category' => "Nonlinear Dynamical Systems",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Condensation/evaporation", 'category' => "Phase change",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Icing", 'category' => "Phase change", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Morphological instability", 'category' => "Phase change",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Solidification/melting", 'category' => "Phase change",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Kinetic theory", 'category' => "Rarefied Gas Flow", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Molecular dynamics", 'category' => "Rarefied Gas Flow",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Combustion", 'category' => "Reacting Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Detonations", 'category' => "Reacting Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Flames", 'category' => "Reacting Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Laminar reacting flows", 'category' => "Reacting Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulent reacting flows", 'category' => "Reacting Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulent boundary layers", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Compressible turbulence", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulence control", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulent convection", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Shear layer turbulence", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Homogeneous turbulence", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Intermittency", 'category' => "Turbulent Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Isotropic turbulence", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulence modelling", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Rotating turbulence", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulence simulation", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Stratified turbulence", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulence theory", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Turbulent transition", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Wave--turbulence interactions", 'category' => "Turbulent Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Vortex breakdown", 'category' => "Vortex Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Contour dynamics", 'category' => "Vortex Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Vortex dynamics", 'category' => "Vortex Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Vortex instability", 'category' => "Vortex Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Vortex interactions", 'category' => "Vortex Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Vortex shedding", 'category' => "Vortex Flows", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Jets", 'category' => "Wakes/Jets", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Separated flows", 'category' => "Wakes/Jets", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Shear layers", 'category' => "Wakes/Jets", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Vortex streets", 'category' => "Wakes/Jets", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Wakes", 'category' => "Wakes/Jets", 'tagtype_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Capillary waves", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Channel flow", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Critical layers", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Elastic waves", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Faraday waves", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Hydraulics", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Wave scattering", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Shear waves", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Solitary waves", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Surface gravity waves", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Wave breaking", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Wave-structure interactions", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")],
                ['name' => "Wind-wave interactions", 'category' => "Waves/Free-surface Flows",
                    'tagtype_id' => 1, 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),
                    'moderated' => date("Y-m-d H:i:s")]
            ]
        );
    }
}